name: Run QC Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.46.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          
      - name: Run report
        run: pixi run test_qc